license="${mod_license}"
issueTrackerURL="https://github.com/Ametrin-Studios/BlockVariantsBWG/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="examplemod.png" #optional
#credits="" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="block_variants"
    type="required"
    versionRange="${bv_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="biomeswevegone"
    type="required"
    versionRange="${bwg_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ametrin"
    type="required"
    versionRange="${ametrin_version_range}"
    ordering="NONE"
    side="BOTH"